apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: talent-app
data:
  REACT_APP_API_BASE_URL: ""
# fe browser url http://k8s-talentap-talentap-d91880f908-1363457137.ap-south-1.elb.amazonaws.com/
# // If API_BASE_URL is already "/api", this creates "/api/api/talents"
# axios.get(`${API_BASE_URL}/api/talents`);