apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: talent-app
data:
  REACT_APP_API_BASE_URL: "http://adf8eab6bdcb744b68205f18d3515bac-999899610.ap-south-1.elb.amazonaws.com:5000"