apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: talent-app
  namespace: argocd
spec:
  description: Talent app project
  sourceRepos:
    - 'https://github.com/satywanbhalekar/helm-talent-app.git'
  destinations:
    - namespace: talent-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'cert-manager.io'
      kind: ClusterIssuer
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'policy'
      kind: PodDisruptionBudget