apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.backend.secret.MONGODB_URI | quote }}
  PORT: {{ .Values.backend.secret.PORT | quote }}
